### ISSUE TITLE
[pandas-project] Carlota portillo

### ISSUE THREAD

**Issue by xarlomi** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#10]

**Comment by xarlomi** [comment]
Link to my repo of 1st project https://github.com/xarlomi/data-cleaning-pandas.git

**Comment by breogann** [comment]
Buenos díaaaaas Carlota! 🙋‍♂️

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .**gitignore**: todo perfect! No se te ha colado ningún archivo temporal/oculto y has metido el csv.
    - Tienes un archivo .txt que no hace nada, no?
- El **[README.md](http://readme.md/) ✍🏻**: te falta entero 🔪. Somos muy pesados con esto, pero es que es muy importante. El día de mañana un recruiter entrará a ver tus proyectos y tiene que saber qué se va a encontrar. Tienes mucha información que dar: intro sobre en qué consiste el proyecto, estructura de los datos antes y después, técnicas de limpieza que has utilizado, librerías, etc.

    También tienes que poner cuáles son las hipótesis que has planteado para limpiar el dataset.

- La **modularización 📉**: en este proyecto no era estrictamente necesario, pero para el resto verás que pediremos que las funciones que se utilicen estén en un ``archivo.py``.
- El **código 👩‍💻:**
    - En general, está súper bien haber comentado los jupyters para ir comentando lo que hacías (unifica el idioma, que lo tienes tanto en castellano como en inglés).
    - Aquí:

        ```python
        data["sex"]= data["sex"].replace(['.', 'na'],['M ', 'M'])
        ```

        ¿por qué sustituyes el sexo . y el sexo 'na' por M?

    - Para esta función:

        ```python
        data = data[[(len(x) < 2) for x in data['sex']]]
        ```

        está genial. Igual podrías haber hecho un apply en vez de sacar la serie y volver a meterla. Con una lambda o una función definida y aplicarla a la columna. Pero vamos, que está genial así también.

    - Esta función:

        ```python
        data[data['fatal (y/n)'].map(lambda x: str(x)!=".")]
        ```

        está súper. Justo lo que te decía antes es que el apply es a los dataframes lo que el map es a las listas. Puedes hacer un apply a la columna o un map a la serie.

        Lo que haces con la función es devolver todo lo que no sea un punto?

    - En vez de replace:

        ```python
        data['fatal (y/n)'] = data['fatal (y/n)'].replace('y','Y')
        ```

        puedes hacer:

        ```python
        df['fatal'] = df['fatal'].apply(lambda x: x.lower())
        ```

    - Muy visual el histplot!
    - Para esta 🤩:

        ```python
        data.groupby('activity').filter(lambda x: 10> len(x)>=1).activity.value_counts()
        ```

    - El jupyter de visualizaión: está lleno de errores y duplicidad. Entiendo que es el borrador que has utilizado y que luego has pasado a limpio en el otro, ¿no?

    Como **conclusión 🦈**:

    - **Te falta el readmeeeeee**
    - Borra el jupyter de visualización y crea otro donde tengas sólo hipótesis, gráficas y conclusiones para tener un story-telling sólido
    - Has hecho una exploración preliminar y has planteado varias hipótesis
    - Has utilizado funciones y has hecho maps y lambdas
    - También has utilizado un montón de funciones de pandas y se ve que tines buen manejo de los datasets

    Está genial el proyecto, sólo algunas cosillas que mejorar. 

    Ánimo Carlota (y a tope, que puedes hacer más y verás que echándole tiempo sacas proyectazos)!! 💪🚀

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
