### ISSUE TITLE
[Pandas-Project]Mario García

### ISSUE THREAD

**Issue by MarioGar25** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#11]
My repo: https://github.com/MarioGar25/project-pandas

**Comment by breogann** [comment]
Buenos díaaaaas Mario! 🙋‍♂️

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .**gitignore**:no tienes .gitignore! por suerte no tienes ningún archivo oculto/temporal que te haya trackeado git.  Pero sí que tienes el attacks.csv que, si sigue el warning, pedían los autores que no se subiera.
    - Todo lo que está en la carpeta de code se puede sacar y dejar en la root.
    - Vale, acabo de ver que tienes el .gitignore pero está dentro de code y dentro de src. Déjalo en la root.
    - Súuper bien por haber exportado las gráficas (ya si las nombras según el contenido 👌)
- El **[README.md](http://readme.md/) ✍🏻**: está súuuper bien. Has introducido el tema, has planteado las hipótesis y has incluido las librerías que has utilizado.
- La **modularización 📉**: en este proyecto no era estrictamente necesario, pero para el resto verás que pediremos que las funciones que se utilicen estén en un ``archivo.py``; tal y como lo has hecho, o sea que genial!
- El **código 👩‍💻:**
    - No importes librerías dentro de funciones!
    - Para el return, si no te interesa el dato, puedes poner un np.nan, si lo que te interesa es un objeto nan (para poder droppearlo)
    - Tienes los jupyters guiados y con comentarios.
    - Súuper bien por utilizar lambdas y apply
    - La visualización está genial también Mario

Está genial el proyecto Mario!! A seguir así! 💪🚀
 ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
