### ISSUE TITLE
[pandas-project] Alex Moreno

### ISSUE THREAD

**Issue by amorenorp** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#12]
Hola!!
Dejo por aquí el enlace a mi repo 🦈 🦈 🦈   : https://github.com/amorenorp/Shark_clean_project

La idea inicial era hacer lago un poco más rebuscado, analizando las columnas con texto como la "especie" , pero no acabó de funcionarme. 

He ido a por algo más genérico y "sencillo"  , aún así me daba errores por todos lados 😆 

![image](https://user-images.githubusercontent.com/74966863/105769631-64f0cf80-5f5e-11eb-93ea-c464f662cd1e.png)

**Comment by olmocorell** [comment]
¡¡Hola Aleeeeeeeeeeex!! 🚀 💪🏻 
La hipótesis era un poco la excusa para que tuviérais por donde tirar, pero bueno, no te preocupes por lo fácil o complicada que te parezca así, a priori.
Aunque bueno, entiendo que a veces, sobre todo al principio, igual nos salen menos cosas de las que queremos hacer.

Te cuento cosinas:

### Readme
Está genial, la verdad es que está perfecto.
Lo único que podrías añadir sería que es un proyecto porque estás estudiando en ironhack y luego, las librerías, añadirlas de tal modo que se vea el nombre y el enlace sea un hipervínculo al que accedemos pinchando en el nombre. Pero bueno, esto te lo digo por ponerme tiquismiquis. Porque está genial.

### Code/Repository structure
La estructura del repo está genial, todo muy bien organizado, aunque no has hecho archivito de funciones....y bueno, en este caso, los notebooks los podías poner a la altura del readme, siendo solo dos, para que estén más accesibles.
Por otro lado, acuérdate de meter el .DS_Store en el gitignore para que no se suba github en las carpetas ¿vale?.


### Code efficiency / Code syntax (conventions)
Te digo por aquí que me ha faltado el archivito de funciones, aunque ya te lo he dicho antes.
Aquí te digo dos cosas:

<img width="764" alt="Captura de pantalla 2021-01-28 a las 8 52 09" src="https://user-images.githubusercontent.com/57899051/106106625-1bfb6f80-6146-11eb-9e83-5f75185095aa.png">

Muy bien la lambda.
El código de debajo.... si se repite ¡¡haz una función!!

Ojito aquí con eliminar los nulls a capón.
<img width="712" alt="Captura de pantalla 2021-01-28 a las 8 52 48" src="https://user-images.githubusercontent.com/57899051/106106690-33d2f380-6146-11eb-84ce-b66148bfe2d8.png">
¡Que nos quedamos sin datos!
Hay una opción muy interesante para eliminar los nulls, que consiste en eliminar los nulls solamente si todas las columnas son null, así te elimina ese registro... pero si eliminábamos todo lo que tenía nulls, ya nos quedábamos prácticamente sin datos, porque todas las filas tenían un null por alguna parte...

El archivo de storytelling está bastante bien. Muy bien apoyarte en los gráficos para contar la hipótesis. Puedes trabajar un poco más el markdown para que se vean títulos y subtítulos y dejarlo un poco más "fino" pero está muy bien Alex.

### Improvements
Has hecho muy buen trabajo, la verdad, así que solo te diría que me ha faltado el archivo de funciones y refactorizar un poquito de código que se repite.
¡El resto a tope!

¡¡Muy buen trabajo!!



![descarga](https://user-images.githubusercontent.com/57899051/106107869-c1631300-6147-11eb-9d7a-d50deb7c4845.jpeg)
