### ISSUE TITLE
[w2-pandas-project] Juan José Triviño Castro

### ISSUE THREAD

**Issue by JJTrivino** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#13]

**Comment by olmocorell** [comment]
¡¡Hola hola Juanjooooo!! 🚀 💪🏻 
En primerito lugar... me has abierto la issue, ok, perfect pero... ¿y el enlace a tu repositorio? jejeje
Bueno, te cuento cositas del proyecto:

### Readme
Puede estar mejor... ¿cómo? pues podrías ponerle una foto de portada, puedes explicar tu hipótesis en el readme. Explicar un poquito mejor el proceso de limpieza de datos y la visualización, incluso contar alguna de las conclusiones...
Y, sobre todo, añadir al final el stack de tecnologías utiliado y un enlace a su documentación (librerías como pandas, seaborn...etc)

### Code/Repository structure
El repo tiene buena estructura, pero acuérdate de que hay algunas cosas que no queremos subir a github y las metemos en el .gitignore para que no se suban ¿vale?
<img width="413" alt="Captura de pantalla 2021-01-28 a las 17 49 32" src="https://user-images.githubusercontent.com/57899051/106170839-30b12500-6191-11eb-8168-a820dadf8490.png">
Luego...aquí tienes un poco de jaleo porque tienes los notebooks, las imágenes...todo mezclado.
<img width="499" alt="Captura de pantalla 2021-01-28 a las 18 07 30" src="https://user-images.githubusercontent.com/57899051/106172965-b209b700-6193-11eb-9f29-c2954693f783.png">

Carpeta de imágenes: las imagenes que quieras exportar
Notebooks: van ubicados en la raíz, si son muchos, hacemos una carpeta de notebooks.
Data: los datos con los que trabajamos.

Vale que dije que el repo podía tener una estructura un poco libre y no hacía falta seguir exactamente la nuestra, pero sí que hay que tener un poco de coherencia con cómo colocamos las cosas.

Luego, si hay un jupyter en el que haces los gráficos, puedes hacer el storytelling ahí, no exportes los gráficos para luego importarlos en otro jupyter...


### Code efficiency / Code syntax (conventions)
Las funciones del archivo de funciones...son muy sencillitas, pero bueno, era un plus, así que...
Tienes un poco mezclado el tema del análisis y de la limpieza.
Me han faltado lambdas y un poco de orden y de estructura, porque realmente has sacado un montón de gráficos que tienen sentido.

### Improvements
- Readme
- Orden y estructura
- Limpieza de los jupyter
- Funciones un poquito más complejas que te pudieran servir


¡Por lo demás enhorabuena! Has hecho muy buen trabajo con pandas, tienes un buen manejo de los dataframes y saber cómo estructurar la información para sacar buenos gráficos. 
¡¡Sigue dándole duro Juanjo!!


![descarga](https://user-images.githubusercontent.com/57899051/106179323-2bf16e80-619b-11eb-9b03-6bafc6c1a3aa.jpeg)
