### ISSUE TITLE
[Pandas-project] Sergio Calero

### ISSUE THREAD

**Issue by SergioCaler0** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#14]
https://github.com/SergioCaler0/pandas-project.git

**Comment by breogann** [comment]
Hola Sergiooo! 🙋🏻‍♂️

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .gitignore:
        - No tienes .gitignore! Aquí te hacía falta por varias razones:
            - Para poder trabajar con el archivo de sharks.csv sin subirlo a github
            - Para ignorar todos los archivos temporales que se te generan: ..ipynb_checkpoints &  __**pycache__.** Recuerda que en el repositorio sólo tienes que tener la información que añada valor.

            Como ya tienes los archivos subidos, quiere decir que están trackeados. Tienes que: borrar el caché de git, añadirlos al git ignore y luego hacer el proceso de add, commit y push. Para borrar archivos de caché:

            ```python
            git rm --cached .ipynb_checkpoints
            git rm --cached __pycache__
            ```

            Para guardarlo en el .gitignore puedes coger cualquiera de los que están en los labs .Te digo esto porque los de los labs están hechos de tal forma que se ignoran de forma recursiva; así da igual que estén dentro de carpetas.

    - Las carpetas de data y de src están perfect. Los jupyters de limpieza y visualización también bien. Yo por preferencia personal los agruparía en otra carpeta y los numeraría para que alguien que entre al repo sepa qué orden seguir. Pero así, al ser dos, está también bien.
- El **[README.md](http://readme.md) ✍🏻**: el readme esta super bien. Has puesto las hipótesis y has "ubicado" al lector en qué se va a encontrar.
    - En la parte de environment, las librerías que has utilizado serían pandas, seaborn, etc. El resto son funciones tuyas que has creado e importado (y está genial, por supuesto), pero no lo pondría en ese apartado. Al final "import src.limpieza_texto as lt" no tiene significado por sí solo. Y es parte de tu código; a mí si me interesa saber qué librerías has utilizado es para saber si las conozco y si me hacen falta descargarlas.
    - Por completitud, puedes añadir si quieres más información sobre la estructura de los datos.
- La **modularización 📉**: ¿somos súper pesados con esto? sí. Has separado las funciones del jupyter y las has llevado a [archivos.py](http://archivos.py) con nombres significativos, o sea que 👏, era lo que pedíamos.
- El **código 👩‍💻:**
    - La limpieza y el story telling:
        - Los jupyter: Están bien guiados con los títulos y los comentarios 🔥.
        - Para ignorar los warnings en el output de los jupyters, puedes poner esto en la celda, antes del código:

            ```python
            %%capture
            ```

        - Si bien has creado un archivo de funciones, son funciones muy sencillas que apenas hacen cosas. Me hubiera gustado algo más de complejidad que el devolver un casteo: return str(x) 😕. Por ejemplo, utilizas una función con regex. Puedes parametrizar esa función para que reciba un argumento que sea el patrón y entonces hacer el apply a la columna.
        - Como te dije en la presentación, echo en falta métricas que acompañen a la visualización. Puedes sacar medias, frecuencias, etc.
        - Las gráficas, ya que las generas, aprovecha a exportarlas! (esto no es necesario, pero no está de más)

            ```python
            fig.savefig("ruta")
            ```

        - Haces algunos replace a mano en la columna de edad. Esto es factible si tienes pocos datos y los puedes identificar, si no, tendrías que utilizar regex, pasarlo a nulos, etc.
        - Genial por haber hecho varios apply!
        - En el jupuyter de visualización, importas el archivo limpio pero te aparece la columna de Unnamed: 0. Al exportarlo, ponle index=False.
        - Las gráficas, como ya te dijo Sheriff, elígelas bien. La última por ejemplo no está devolviendo información significativa. El resto están genial, pero sí que me falta la parte de storytelling. Has seleccionado las que te valían para las hipótesis, pero le puedes meter más chicha a la hora de ir expplicando por qué eliges una u otra, si falsan o la hipótesis que habías planteado, etc.

    Está bien Sergio! le añadiría más funciones y un story-telling a modo de resumen/conclusión (y quita los archivos temporales del repo!). Quizá alguna hipótesis más para poder hacer más limpieza. Ánimo con el siguiente proyecto Sergio, seguimooooss!! 💪

    ![image](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
