### ISSUE TITLE
[ w2-pandas-project]JeancharlesYamada

### ISSUE THREAD

**Issue by yamadajc** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#15]
https://github.com/yamadajc/data-cleaning-pandas

**Comment by olmocorell** [comment]
¡¡Hola Hola Yanchaaaaaaaaaaaaaa 🚀 💪🏻 !! 
En primerito lugar, te pido disculpas por haber venido tan tarde por aquí a corregirte este proyecto. Espero no vuelva a pasar.
Te cuento cositas

### Readme
No está mal, porque está, pero... puedes contar que es un proyecto del bootcamp de data analyst de ironhack, puedes meterle una fotito de portada y puedes también poner enlaces al stack de tecnologías utilizado.
En plan:
Para ello manejo estas librerías:
- [Pandas](https://pandas.pydata.org/docs/)
- blablabla


### Code/Repository structure
La organización del repositorio está perfecta. Y la estructura del código en principio no te la evalúo en este proyecto, porque no hay archivo de funciones, ya que era un plus. No pasa nada. Para este proyecto ya le tienes que estar dando duro a eso....
Tengo que decirte, que revisando por encima los jupyter antes de meterme a fondo con ellos, está MUY BIEN el jupyter de limpieza todo comentado y todo hecho por pasos.

### Code efficiency / Code syntax (conventions)
Vamos con la eficacia del código.
Enhorabuena por esto:
<img width="663" alt="Captura de pantalla 2021-01-31 a las 13 54 08" src="https://user-images.githubusercontent.com/57899051/106384567-cdf79d80-63cb-11eb-83dc-0bc35378bba2.png">
Es muy importante revisar lo que nos cargamos y hacerlo a conciencia, no podemos eliminar filas simplemente porque tengan nan, si no que debemos fijarnos que todos los registros sean nan, porque si no, nos quedamos sin datos.

En cuanto al jupyter de limpieza, está muy bien Yancha, está genial. Todo comentado y el uso del markdown, es así como pedíamos que lo hicierais y es así como se debe de hacer, para poder seguir el hilo de lo que vas haciendo. Está genial.

Luego, el jupyter de visualización está más regu, porque... ¡¡no hay historia!! no hay gráficos...
Y me da rabia, porque estabas contando una historia. Es decir, hay compañeras que han hecho gráficos, pero sin historia. Tú tenías una buena limpieza y una historia. Y me ha hecho mucha gracia que sacaras los ataques de gente mirándose los pies. jajaja es que....te han faltado los gráficos, que eran un poco indispensables en este proyecto para hacer un proyecto redondo. Porque tu carisma, cómo has aplicado el código y el orden y estructura (la meticulosidad) hacen un combo perfecto.
Pero bueno, este finde le estarás dando a saco a los gráficos, espero. O le darás entre hoy y mañana.
Es mejor hacer un par de gráficos o 3 diferentes, que nos pinten lo que estamos contando, a hacer un montón de gráficos sin sentidos. Utilízalos a tu favor para contar tu historia.

### Improvements
- Portada y documentación en el readme
- Gráficos
- Alguna funcioncita

¡¡Enhorabuena Yancha!! tengo muchas, muchas ganas de verte evolucionar en el bootcamp, porque tienes una actitud de las que ya no se ven por aquí y es lo fundamental para pasarse ironhack en nivel pro. La curva de aprendizaje depende del esfuerzo y me consta que lo estás haciendo a muerte. Y ver esa actitud desde este lado hace que nuestro día a día tenga sentido.
Así que ¡¡¡¡Buen trabajo!!!!! ¡¡Y SIGUE ASÍ!!

![descarga](https://user-images.githubusercontent.com/57899051/106385771-39dd0480-63d2-11eb-82a2-938745be13b9.jpeg)
