### ISSUE TITLE
[w2-pandas-project]Ana G. 

### ISSUE THREAD

**Issue by AnaAGG** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#17]
https://github.com/AnaAGG/Pandas.git

**Comment by olmocorell** [comment]
¡¡Hola hola Anaaaaaaa!! 🚀 💪🏻 
Te cuento unas cosinas del proyecto:

### Readme
¡Está genial! Enhorabuena, un readme que invita a seguir leyendo y a "bucear" (je) en el proyecto. 
Si me pongo tiquismiquis, cuando mencionas las librerías puedes meterle ahí directamente el enlace a la documentación, pero vamos, que está genial

### Code/Repository structure
Está muy bien el archivo de funciones, tienes cosas muy interesantes.
Aunque....se llama funciones.py (aunque en inglés). 
Bueno, en este caso lo perdonamos, porque era un plus, pero normalmente ponemos nombres descriptivos de lo que hay dentro a los archivos de funciones...¿vale?
Ya sabes que hay ahí mucho if y mucho elif que se pueden refactorizar simplemente con diccionarios. Lo vemos estos días sin fallo. Ya he estado echando un ojo a esas funciones y verás que es fácil. En cuanto tengamos un ratin nos ponemos con ello.

### Code efficiency / Code syntax (conventions)
En cuanto a eficiencia del código, vale, a ver. Lo del if y el elif que ya te he contado.
Y luego, por aquí:
<img width="1077" alt="Captura de pantalla 2021-01-28 a las 17 15 13" src="https://user-images.githubusercontent.com/57899051/106166382-66074400-618c-11eb-9efe-f4913ff8e263.png">
Igual, cuando repetimos código, podemos hacer funciones. 

En general el archivo de limpieza es una auténtica pasada. Has currado un montonazo, la verdad. Enhorabuena.
Muchas de las cosas que pones en comment # o """ se puede meter haciendo que la celda sea en formato markdown
Pero bueno, que eso en cuanto a eficiencia del código está genial.

Estas funcioncitas las puedes meter al archivo de funciones:
<img width="740" alt="Captura de pantalla 2021-01-28 a las 17 19 44" src="https://user-images.githubusercontent.com/57899051/106166977-05c4d200-618d-11eb-8ea8-1ef14682a95c.png">
Los gráficos están genial... ¡¡¡pero genial!!! muy buen trabajo con eso

### Improvements
Te pongo aquí unas poquitas mejoras, pero es poco, porque en general has realizado muy muy buen trabajo.
- Atomización del código en funciones (cuando el código se repite, hacemos funciones)
- Todas las funciones en ficheros .py y en el jupyter simplemente las llamadas
- Explicación con markdown en el jupyter de limpieza
- Un poco más de "contar una historia" o "vender" metiendo "fantasía" a modo de explicación de los gráficos.

¡¡Muy buen trabajo!! En cómputo general, este proyecto está de sobresaliente. ¡¡Enhorabuena!!

![descarga](https://user-images.githubusercontent.com/57899051/106167672-baf78a00-618d-11eb-8401-d928c83e591b.jpeg)
