### ISSUE TITLE
[w2-pandas-project] Alfredo Zavala

### ISSUE THREAD

**Issue by alfredozavala14** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#18]
https://github.com/alfredozavala14/IronH-Project-1.git

**Comment by olmocorell** [comment]
¡¡Hola Hola Alfredoooooooooo!! 🚀 💪🏻 
Te cuento cositas del proyecto....

### Readme
Está perfecto enhorabuena, así es como se hace un readme. Perfecta estructura, uso del markdown y los enlaces a la documentación.
¡¡Enhorabuena!!

### Code/Repository structure
El repo está bien organizado, lo único que me descuadra son los jupyter notebooks en la carpeta "output", me ha costado encontrarlos, porque no los esperaba ahí.
La carpeta output debería ser más bien para lo que nuestro proyecto genera. Es decir, si exportamos gráficos o sacamos algún extracto concreto de los datos..
Al archivo de funciones normalmente le ponemos un nombre más descriptivo ¿vale? esto lo veremos en proyectos en los que tengamos diferentes archivos de funciones. En este, como era un plus... pues te lo paso.


### Code efficiency / Code syntax (conventions)
Las funciones del archivo son muy sencillitas, tienes nivel para hacer funciones más complejas, pero aún así, enhorabuena por haber hecho un archivito.
Esto está guay pero.... si el código se repite, es porque es susceptible de ser atomizado en una función:
<img width="992" alt="Captura de pantalla 2021-01-28 a las 9 38 43" src="https://user-images.githubusercontent.com/57899051/106111674-9fb85a80-614c-11eb-98e0-2156fc963c56.png">
Y abajo igual, podías hacer una función con todos los str.replace.

En el archivo de visualización veo algunos gráficos que me explican cosas y me gusta, también veo que todo está narrado y explicado de forma ordenada y que se puede seguir la historia.
¡¡Enhorabuena!! Eso está realmente genial.
Podías haber probado a hacer algún gráfico más y ponerle un poquito más de "fantasía" porque creo que tienes mucho nivel y por ponerme tiquismiquis. Pero está genial.

### Improvements
Te dejo el espacio de mejoras vacío, porque tu proyecto está muy muy bien, solo anota el par de cosas que te he dicho...bueno
- Atomización de funciones
- Un pelín más de fantasía


¡¡Muy buen trabajo Alfredo!! ¡Sigue así!

![descarga](https://user-images.githubusercontent.com/57899051/106112119-28cf9180-614d-11eb-84b4-d6ee9387e167.jpeg)

**Comment by alfredozavala14** [comment]
Muchas gracias por los comentarios aquí y en todos los labs!! Lo estoy revisando ahora
Tienes razón con lo de la fantasía pero voy como un zombie por la vida... estoy haciendo un MBA en Londres a la vez que el bootcamp y la verdad es que está siendo muy extremo hacer las dos a la vez... pero bueno cuando pueda intentaré hacer cosas más chulas!
