### ISSUE TITLE
[Pandas-project] Floren Gutiérrez

### ISSUE THREAD

**Issue by florengutierrez** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#19]
https://github.com/florengutierrez/Pandas-Project

**Comment by breogann** [comment]
Buenos díaaaaas Floren! 🙋‍♂️

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .**gitignore**: se te han colado archivos ocultos/temporales dentro de la carpeta de data. Para eliminarlos, primero tendrás que "destrackearlos" de git. Para eso:

        ```python
        git rm --cached .DS_Store
        git rm --cached .ipynb_checkpoints
        ```

        en el gitignore tendrás que decirle que los ignore también si están dentro de carpetas.

        ```python
        **/.DS_Store
        **/*.ipynb_checkpoints/
        ```

    - En la carpeta de data guarda sólo los datos como tal. El input/output que proceses. El jupyter donde haces el resto puedes dejarlo fuera; o si tienes varios, meterlo en una carpeta de notebooks.
- El **[README.md](http://readme.md/) ✍🏻**: súuper bien Floren! Has introducido en qué consiste el proyecto y has plantado las hipótesis. Está genial. Por meterle más miga, añadiría:
    - La fuente original de los datos
    - Los datos en sí, qué estructura tienen
    - Cómo quedan después de haberlos limpiado
    - Técnicas de limpieza
    - Librerías utilizadas
    - Gráficas que hayas generado
- La **modularización 📉**: en este proyecto no era estrictamente necesario, pero para el resto verás que pediremos que las funciones que se utilicen estén en un ``archivo.py``.
- El **código 👩‍💻:**
    - En general, está súper bien haber comentado los jupyters para ir comentando lo que hacías.
    - Aquí:

        ```python
        Gender_col = data[data["Sex"].isin(["M","F"])]["Sex"].value_counts()
        ```

        estás comprobando los números, pero no estás haciendo limpieza como tal. O sea, estás visualizando los datos pero sin modificarlo.

    - Has exportado las gráficas 👏 pero no están en el repo! aprovecha y guárdalas en una carpeta de output
    - En esto:

        ```python
        data["Fatal (Y/N)"] = data["Fatal (Y/N)"].str.replace('2017', 'UNKNOWN')
        data["Fatal (Y/N)"] = data["Fatal (Y/N)"].str.replace('M', 'UNKNOWN')
        data["Fatal (Y/N)"] = data["Fatal (Y/N)"].str.replace('nan', 'UNKNOWN')
        data["Fatal (Y/N)"] = data["Fatal (Y/N)"].str.replace('y', 'UNKNOWN')
        ```

        siempre que escribas varias líneas muy parecidas, es porque probablemente se puede refactorizar. Puedes poner la condición de que no sea ni "y" ni "x". ¿Por qué pasas la "y" a unknown?

    - Respecto a los gráficos, no solemos ser muy fan de los pieharts. Prueba mejor con histogramas para los siguientes!

    Como **conclusión 🦈**:

    - Está genial el readme
    - Procura no utilizar piecharts
    - Están bien guiado el jupyter
    - Puedes meter lambdas/funciones y hacer applys! siempre se puede hacer algo más de limpieza

    Está bien el proyecto, sólo algunas cosillas que mejorar. 

    Ánimo Floren (y a tope, que puedes hacer más y verás que echándole tiempo sacas proyectazos)!! 💪🚀

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
