### ISSUE TITLE
[pandas-project] Antonio García

### ISSUE THREAD

**Issue by antoniogarciagiron** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#2]
https://github.com/antoniogarciagiron/Project-Pandas-Shark-Attack.git

**Comment by olmocorell** [comment]
¡Buenos días Toniiiiiiiiii! 🚀 💪🏻 
No me voy a explayar mucho por aquí porque ayer te dimos feedback en clase.
¡¡Enhorabuena por tu proyecto!!

Recuerda que está muy bien que hayas hecho varios archivos de funciones y que tengas varios gráficos.
En cuanto a mejoras, recuerda que te dijimos el tema de los import y que hay alguna funcioncita que se puede refactorizar. El uso de los diccionarios es muy útil... y el tema del "NaN" en string...
Tus gráficas estaban muy bien, porque mostraban lo que querías demostrar con los datos. ¡¡El readme genial!!

¡¡Seguimoooooooooos!!


![descarga](https://user-images.githubusercontent.com/57899051/106102783-33375e80-6140-11eb-9f0f-e9aa775df8e7.jpeg)
