### ISSUE TITLE
[Pandas project] MARINA D

### ISSUE THREAD

**Issue by Marina-Diez** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#3]
https://github.com/Marina-Diez/-Pandas-project-MARINA-D

Empezamos!!

**Comment by Marina-Diez** [comment]
dejo mi repo aqui:
https://github.com/Marina-Diez/Panda-Project-MARINA-D

**Comment by olmocorell** [comment]
¡¡Hola hola Marinaaaaaaaa!! 🚀 💪🏻 
¡¡Te cuento cositas de tu proyectoooooo!!

### Readme
Está muy muy bien. Con las imágenes de portada, la explicación y haces un buen uso del markdown. También es muy buena idea la de cargar algunos de los gráficos que ha generado el proyecto en el readme para que ya se vea parte del trabajo que se va a encontrar dentro y llamar la atención.
Lo único que, por ponerme tiquismiquis y aportarte un poquito, a la hora de meter la documentación, lo que yo haría es, en vez de poner "import pandas....", pondría, el stack de tecnologías que he utilizado es:
- [pandas](https://pandas.pydata.org/docs/)
- blablabla
Y todo esto con enlaces a la documentación, 


### Code/Repository structure
La estructura del repositorio está perfecta, la verdad. Gracias y ¡¡enhorabuena!! 


### Code efficiency / Code syntax (conventions)
Está genial el archivo de funciones, que no lo hayas llamado funciones.py, y me gusta cómo has hecho la categorización de los tiburones. Enhorabuena.
Muy muy bien esta exploración de los "missing data"
<img width="845" alt="Captura de pantalla 2021-01-29 a las 12 25 22" src="https://user-images.githubusercontent.com/57899051/106269650-12006c00-622d-11eb-9565-4e1cecceebf3.png">

Esto, MUY BIEN. Si borramos los nan sin poner el how o lo hacemos con `how="any"` nos quedamos prácticamente sin datos, y eso no lo queremos.
<img width="565" alt="Captura de pantalla 2021-01-29 a las 12 26 02" src="https://user-images.githubusercontent.com/57899051/106269716-280e2c80-622d-11eb-89e6-efaa59203f83.png">

Aquí: 
<img width="1039" alt="Captura de pantalla 2021-01-29 a las 13 06 01" src="https://user-images.githubusercontent.com/57899051/106273324-bdf88600-6232-11eb-9c89-947309ecfbc6.png">
Si solo vas a coger 3 columnas porque son las relevantes, creo que es más útil hacerlo de forma inversa, coger las que quieres en vez de borrar las que no quieres... puedes hacer un drop de lo que no esté en la lista de lo que quieres o machacar la variable diciendo que sean esas 3 columnas o incluso hacer una copia.

Lo demás está todo perfecto.
Para añadirte alguna mejora, te puedo decir que en el jupyter de visualización puedes meter más comentarios en markdown para contar la historia de los datos. 
Pero en general está muy bien, está de sobresaliente, de verdad.

### Improvements
- Enlaces a documentación en el readme
- Fantasía en el story telling

¡¡Enhorabuena por tu trabajo!! ¡¡Sigue asíííííííííííí!!


![descarga](https://user-images.githubusercontent.com/57899051/106273716-69a1d600-6233-11eb-885d-2e4d4d99a21e.jpeg)
