### ISSUE TITLE
[pandas-project] Xabier Arrieta

### ISSUE THREAD

**Issue by XabierArrieta** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#4]
https://github.com/XabierArrieta/Pandas

**Comment by olmocorell** [comment]
¡¡Hola Hola Xabiiiiiiiiii 🚀 💪🏻 !! 
En primer lugar, te pido disculpas por haber tardado tanto en venir a corregirte el proyecto. Quería tenerlo antes de presentar el siguiente para que te sirvieran los consejos. Aún así, espero llegar a tiempo y espero que no vuelva a pasar.

### Readme
Está genial, casi perfecto, la verdad.
¿Qué añadiría yo para que estuviera redondo? Una imagen de portada, no es obligatoria, pero llama mucho la atención.
Enlaces a la documentación en el apartado de librerías.
Por lo demás, está genial. Muy bien Xabi!! 🔝 


### Code/Repository structure
La estructura del repositorio está perfecta, solo te pongo un par de pegas.
La carpeta .vscode métela en el gitignore para que no se suba a github ¿vale?
Por otra parte, tienes un Untitled.ipynb ... así, de primeras ¿qué hay dentro? (ahora lo descubriré) pero, lo que te quiero decir... no subimos untitled ¿vale? .
En cuanto a estructura del código no te digo nada, porque esto va relacionado con los .py y las funciones que metemos en ellos, como en este proyecto era un plus, pues nada que decir en cuanto a esto.

### Code efficiency / Code syntax (conventions)
Por otra parte:
<img width="930" alt="Captura de pantalla 2021-01-31 a las 15 07 12" src="https://user-images.githubusercontent.com/57899051/106386588-0308ed80-63d6-11eb-8fbd-44b902e2c7e9.png">
¿Por qué no hacer esto? Porque mira, si te fijas, tener un dataset de 25.700 filas y reducirlo a 3.000 es quedarte con el 12% de los datos. ¡¡Te quedas solo con el 12%!! y aunque es verdad que el dataset está súper sucio, igual podrías haber hecho otras cosas con los NAN.
Por ejemplo, utilizar la columna date para apoyarte en la de YEAR y hacer una especie de "merge" cogiendo la info de las dos columnas para tenerlo más completo... y utilizar la categoría "unknown" para casos en los que te falten datos. Pero, imagínate que te falta el sexo en 2.000 filas, puedes poner sexo desconocido pero realmente son 2.000 ataques que estás eliminando... ¿entiendes esto?
Para esto, al hacer dropnan hay un parámetro que es "how" y ahí puedes darle varias opciones, si hacemos dropna con how all, se borran las filas en las que TODO es NaN, porque realmente, el resto de filas sí que son aprovechables...de alguna manera. La idea del mundo del data es aprovechar toooooodos los datos que tengamos, o intentarlo, y trabajar con cuantos más datos, mejor. 

El resto está realmente bien...la organización, la esrtructura, cómo vas contando la limpieza, y cómo te vas haciendo un montón de gráficos para ir teniendo realmente idea de cómo están los datos. 
<img width="714" alt="Captura de pantalla 2021-01-31 a las 15 19 11" src="https://user-images.githubusercontent.com/57899051/106386936-aeff0880-63d7-11eb-93c2-fa847e4785a6.png">

El archivo de visualización está también MUY BIEN. Eso sí, está un poquito desaprovechado, porque tenías gráficos MUY chulos en el jupyter de limpieza que podías haber dejado en el de visualización y apoyarte en ellos para contar tu historia. Tenías un montón de material.
Hay otros que no, como este, por ejemplo, que es un poco caos, pero está genial que hayas probado a hacerlo para ver cómo quedaba:
<img width="1015" alt="Captura de pantalla 2021-01-31 a las 15 26 24" src="https://user-images.githubusercontent.com/57899051/106387151-b1ae2d80-63d8-11eb-9c8b-f4670395430d.png">

En general, lo que veo en este proyecto es un trabajazo increíble, Xabi. De verdad.
Lo único que te pongo de mejora es, que en el jupyter de visualización podías haber metido un poquitititito más de fantasía (algunos gráficos más y más descripción en la historia, más narrativa).
El archivo de funciones y las funciones fuera del jupyter eran opcionales en este proyecto, así que no pasa nada.

### Improvements
- Enlaces a documentación en el readme
- Gráficos que tienes en limpieza utilizados para apoyarte a contar la historia en el de visualización.
- Un poco más de narrativa y explicación de los gráficos.


Enhorabuena Xabi, de verdad que veo muchas muchas horas echadas en este proyecto. Mucho trabajo y muy meticuloso. 
Está muy bien. ¡¡¡SIGUE ASÍ!!! Estoy súper contenta de haber corregido tu proyecto.
¡Vamooooooooooooooossss!

![descarga](https://user-images.githubusercontent.com/57899051/106387268-4fa1f800-63d9-11eb-9495-b565bd276603.jpeg)
