### ISSUE TITLE
[Pandas-Project] Santiago Hartmann

### ISSUE THREAD

**Issue by santhart97** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#5]
https://github.com/santhart97/Project.1-Pandas

**Comment by olmocorell** [comment]
¡¡Hola Hola Santiiiiiii!!  🚀 💪🏻 
¡Te cuento cositas del proyecto!


### Readme
El readme está bastante bien, lo único que podrías añadir sería una imagen de portada arriba del todo y algunos enlaces a la documentación del stack de tecnologías que has utilizado. 


### Code/Repository structure
Esto está peor... el repositorio no tiene estructura, no tienes el sistema de organización de carpetas y tienes todos los archivos sueltos y mezclados...
Lo ideal es que los archivos jupyter estén fuera, a la altura del readme. 
Este sería un ejemplo de un repositorio bien organizado:
<img width="682" alt="Captura de pantalla 2021-01-31 a las 12 54 35" src="https://user-images.githubusercontent.com/57899051/106383010-7ce3ab80-63c3-11eb-8f1b-b16fc5d20f57.png">


### Code efficiency / Code syntax (conventions)
El código está basante bien en cuanto al análisis exploratorio. He echado de menos alguna función, que hubieras usado regex para limpiar y que hubieras aplicado alguna lambda.
También aplicar funciones escritas por ti a diversas columnas de un dataframe con un .apply

Veo que en el archivo de visualización has hecho una función con regex y la aplicas con un .apply justo como te estaba diciendo.
Esto deberías haberlo hecho en el jupyter de limpieza.

El archivo de visualización tendría que estar ya limpio y bonito y encontrar solo el código que tenga que ver con los gráficos, los gráficos en sí y la explicación de los gráficos. 
Pero los gráficos están bastante bien, la verdad.

### Improvements
- Detalles del readme
- Organización del repo
- Funciones / .apply lambdas (para practicar un poco más)
- Organización y limpieza de los jupyter notebook

En general has hecho un buen trabajo, realmente son unos pequeños detalles, si ordenas el repositorio y organizas los jupyter notebook el proyecto está muy bien. La hipótesis es bastante original y los gráficos te han quedado genial
¡¡Buen trabajo!! Intenta ser más ordenado en el siguiente proyecto, es muy importante.
¡Sigue así Santi!


![descarga](https://user-images.githubusercontent.com/57899051/106384033-4b6dde80-63c9-11eb-9e79-e1e36ba32601.jpeg)
