### ISSUE TITLE
[pandas_project_2] Cristina Callejo

### ISSUE THREAD

**Issue by CristinaCallejo** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#6]
https://github.com/CristinaCallejo/hugging_pandas.git

(aprenderé a hacer memes en el concurso, por ahora #dejasenjas y tiro porque me toca.

**Comment by breogann** [comment]
Hola Cristinaaa! 

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .gitignore:
        - Tienes archivos por ignorar. Hay algunos que has puesto en la misma línea, así que no te los está leyendo.

            Como ya tienes los archivos subidos, quiere decir que están trackeados. Tienes que: borrar el caché de git, añadirlos al git ignore y luego hacer el proceso de add, commit y push. Para borrar archivos de caché:

            ```
            git rm --cached .ipynb_checkpoints
            git rm --cached .DS_Store

            ```

            Para guardarlo en el .gitignore puedes coger cualquiera de los que están en los labs. Te digo esto porque los de los labs están hechos de tal forma que se ignoran de forma recursiva; así da igual que estén dentro de carpetas.

            También has subido el zip con el dataset. En kaggle pedían que no se subiera (si sigue el warning todavía puesto). En cualquier caso, si lo subes y es sólo el csv, súbelo descomprimido (si tu intención es que se vea).

            Vamos, en el repo sólo lo que añada valor.

    - Para los notebooks, yo los agruparía en un carpeta y los ordenaría:

        ```jsx
        1-cleaning.ipynb
        2-visualization.ipynb
        ```

        para que cuando alguien entre a ver tu repo, pueda navegarlo y entender el proyecto.

- El **[README.md](http://readme.md/) ✍🏻**: has creaddo un archivo que no tiene extensión de mardkwon (.md) y que no se llama`README.md`. Esto es una convención y es la que utiliza github para "renderizar" la portada. Además lo has tratado como un archivo de texto, sin sintaxis de markdown 🔪 esto cámbialo, es importante! Explicita también cuáles son las hipótesis y si se cumplen.
- La **modularización 📉**: ¿somos súper pesados con esto? sí. Has separado las funciones del jupyter y las has llevado a [archivos.py](http://archivos.py/) con nombres significativos, o sea que 👏, era lo que pedíamos. Para el siguiente proyecto pediremos la parte de los docstrings:

    ```python
    def hacer_cosas():
    	''' Esta función hace cosas.
    Takes: cosas
    Returns: otras cosas'''
    	return algo
    ```

- El **código 👩‍💻:**
    - La limpieza y el story telling:
        - En el jupyter de clean1.ipynb, hsa hecho una exploración preliminar de los datos y algunos drop, pero no hay apenas limpieza.

            Sí que has hecho renaming de las columnas, dropping, replace de la columna fatality y la transformación a numeric (👏), pero me habría gustado alguna manipulación más de los datos; el resto son value_counts/info/shape que has hecho para explorar los datos. Ten en cuenta que esto tiene que ser algo guiado para alguien que entre al repositorio. Ponle también títulos al notebook y más comentarios. 

        - Para la visualización:
            - El primer countplot que haces, no se pueden ver las etiquetas del eje X. Puedes o bien crear grupos de edadse, elegir otra etiqueta para que se vea mejor u otro tipo de plots (como usas más adelante el histplot!).
            - ¿Los invalid o unknown? ¿te hacen falta? igual los puedes pasar a nulos.
        - El código:

            ```python
            return: lambda value: value == df2['column_name'].median()
            ```

            cuidado con los dos puntos tras el return.

            Aquí:

            ```python
            def ccategorize(df):
                for [column] in df:
                    column=column.astype('category')
                return
            ```

            no tienes return. También estás iterando por cosas en el df. "for in in df", ¿con eso, qué quieres conseguir? 😶

            - Genial por haber puesto el índice en falso el exportarlo:

            ```python
            df2.to_csv('Sharks_selected.csv', index=False)
            ```

    Como conlusiones, te diré:

    - Hace falta modificar la estructura: quitar archivos ocultos, organizar código por carpetas (notebooks vs. archivo.py) y también hacer el readme.
    - En src has hecho tan sólo un par de funciones y tampoco están completas
    - En los jupyter, sólo has planteado una hipótesis y apenas has hecho limpieza. Echo en falta más funciones y más hipótesis
    - Para la visualización, has probado varios tipos de histogramas, pero tampoco puedes visualizar mucho más al tener sólo esa hipótesis
    - Tampoco hay un story-telling o una explicación guiada de lo que has ido haciendo. Como os decía, que un/a amiga/o vuestra/o sea capaz de entender qué habéis hecho sin saber nada de código.

    Si sacas un rato a lo largo del bootcamp (o cuando lo acabes) dale una vuelta al proyecto para que quede más completo. Cualquier cosa nos dices. Ánimo Cristinaaa 💪

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
