### ISSUE TITLE
[pandas-project] Ana de Luna

### ISSUE THREAD

**Issue by AnadeLuna** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#7]
https://github.com/AnadeLuna/Proyecto-Pandas

**Comment by breogann** [comment]
Hola Anaa! 🙋🏻‍♂️

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: está perfecto. No has subido ningún archivo oculto/temporal a github, o sea que estupendo.
    - Tampoco has subido el csv original, como pedían los autores de kaggle
    - Sí que tienes un archivo de Untitle.ipynb que entiendo que era para pruebas. Si no lo necesitas, puedes eliminarlo.
    - Las carpetas de data y de src están perfect.
- El **[README.md](http://readme.md/) ✍🏻**: el readme esta super bien. Has "ubicado" al lector en qué se va a encontrar.
    - Para la parte de las hipótesis, has mencionado lo que vas a explorar, pero no llegas a plantearlas. Explicita qué es lo que quieres buscar.
    - Por la parte visual, puedes utilizar "bullet points" (como estos), utilizar negrita, etc. Es muy fácil em markdown. La imagen no se te ha renderizado porque te falta comenzar esa línea con una exclamación (y porque el enlace va entre paréntesis, no corchetes): [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/)
    - Comentas que pondrás gráficos pero se te olvidó ponerlos.
    - Por completitud, puedes añadir si quieres más información sobre la estructura de los datos.
- La **modularización 📉**: ¿somos súper pesados con esto? sí.  La cosa es coger las funciones que has utilizado en jupyter, definirlas de forma genérica en src/limpieza.py y luego importarlas en el jupyter.

    Tal y como lo tienes, tienes una carpeta de src y otra de jupyters. No tengo del todo claro el por qué de la división 😶. Si son borradores, quítalos. Todo lo que no añada valor al repositorio, déjalo fuera.

- El **código 👩‍💻:**
    - La limpieza y el story telling:
        - Los jupyter: Están bien guiados con los títulos y los comentarios 🔥.
        - Si a partir de la file 6301 es nulo, no lo quites con iloc 🙅‍♂️, quítalo con dropna, con .isnull(), etc. Utiliza funciones en vez de hacerlo "a mano".
        - Genial el uso de apply y lambdas!

            ```python
            year = data4["Year"].apply(lambda x: int(x))
            ```

        - Para esto:

            ```python
            data10[data10["Sex "] == "M "] = "M"
            data10[data10["Sex "] == "lli"] = "Null"
            data10[data10["Sex "] == "."] = "Null"
            data10[data10["Sex "] == "N"] = "Null"
            data10["Sex "].unique()
            ```

            puedes crear una función de tal forma que:

            - El input que entra a la función le haces un .strip() para eliminar espacios
            - Lo pasas todo a mayúscula o minúscula
            - Y si ese input no se corresponde con M o F, haces que devuelva NaN

            Como le dije a Toni, devolver un "Null" en string no tiene significado a nivel de programación. Cuando sacas el df tú lo lees como que es "Null", pero no es un objeto como tal con el que puedas operar. Es decir, si tú haces .isnull(), esos valores no te los devuelve, porque son strings como podían ser cualquier otra palabra.

            - No dejes los errores!
        - Para limpiar los meses, están repitiendo muchas líneas: siempre que escribas muchas veces un input parecido, probablemente lo puedas refactorizar en una función. Ahí estás sustiuyendo, peor puedes sumplemente quitarles el guión. Igual que antes utilizabas una lambda, puedes utilizar otra para devolver todo menos la último posición.

            ```python
            lambda x: x[:-1]
            ```

            y como se lo quieres pasar a toda la columna, le puedes hacer un apply.

        - Genial por hacer un resumen al final del jupyter!
        - En el jupyter de la visualización, si no puedes ordenarlo por mes, puedes sustituir los meses por los números.
        - Los diagramas como el scatterplot no te está dando ninguna información significativa, ojo con eso!
        - Por lo demás, has hecho visualización pero te falta la parte de story-telling. Sí que está la información guiada y con títulos, pero intenta dar más información sobre las hipótesis: ¿se han falsado? Tenías unas preguntas de investigaión, tienes que dar una respuesta, aunque la respuesta sea "inconclusive".
        - Las gráficas, ya que las generas, aprovecha a exportarlas! (esto no es necesario, pero no está de más)

            ```
            fig.savefig("ruta")

            ```

    Está bien Ana! le añadiría más funciones y un story-telling a modo de resumen/conclusión. Quizá alguna hipótesis más para poder hacer más limpieza. Para el siguiente proyecto sí que pediremos sí o sí que las funciones estén modularizadas en arhcivos.py (que pasen del jupuyter a estar definidas en otro archivo). 
    
  Ánimo con el siguiente proyecto Anaa!! 💪

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
