### ISSUE TITLE
[w2-pandas-project] Sonia Garcia Fominaya

### ISSUE THREAD

**Issue by Fominayasg** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#8]
https://github.com/Fominayasg/w2-pandas-project-Sonia-Garcia-.git

**Comment by breogann** [comment]
Hola Sonia!

Tienes el proyecto vacío. ¿Te olvidaste de hacer el push?

**Comment by breogann** [comment]
Hola Soniaa! 🙋🏻‍♂️

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: está perfecto. No has subido ningún archivo oculto/temporal a github.
    - Tampoco has subido el csv original, como pedían los autores de kaggle
    - Sí que tienes un archivo de Untitle.ipynb que entiendo que era para pruebas. Si no lo necesitas, puedes eliminarlo.
    - Las carpetas de data y de src están perfect.
    - Para los jupyter, te diría que lo organizases para la próxima como una carpeta de notebooks y que los numeres. Al final siguen una secuencia lógica: 1-exploracion, 2-cleaning, 3-metrics, etc.
- El **[README.md](http://readme.md/) ✍🏻**: el readme enfocalo másomenos como un artículo científico: abstract, introducción, métodos, , resultados, conclusiones, etc. Tienes info sobre todo: lo que has hecho, qué estructura tienen los datos, qué técnicas has utilizado, qué resultados has obtenido. Y **las hipótesis**.
- La **modularización 📉**: ¿somos súper pesados con esto? sí.  La cosa es coger las funciones que has utilizado en jupyter, definirlas de forma genérica en src/limpieza.py y luego importarlas en el jupyter. Para este proyecto no era necesario, ya verás que lo pediremos para el resto.
- El **código 👩‍💻:**
    - La limpieza y el story telling:
        - Los jupyter: Están bien guiados con los títulos y los comentarios 🔥.
        - Esta función? 😳:

            ```python
            #Percentage of nulls of each column
            perc_null = attack.isnull().sum().apply(lambda x: x/attack.shape[0]).sort_values(ascending=False)
            ```

            te has marcado métodos de pandas, apply y lambda, o sea que muy top.

        - Para saber si tienes columnas duplicadas, puedes utilizar booleanos para ver la relación de igualdad. Pero con que haya sólo un espacio que no coincida en una celda de las 25723 filas, te diría que no está duplicado. En cualquier caso te has lanzado a hacer una pedazo de función para sacarlo. En vez de que te devuelva una lista, puedes hacer que te devuelva True o False.
        - Para esto:

            ```python
            attack2['Fatal (Y/N)'].replace({' N': 'N', 'N ': 'N', '2017': 'UNKNOWN', 'M' : 'UNKNOWN', 'NaN' : 'UNKNOWN'}, inplace=True)
            ```

            puedes utilizar el método .strip() para eliminar los espacios, así no tienes que tener en cuenta todas las permutaciones de las letras con espacios antes y delante.

        - Están muy bien separados los jupyters. En la limpieza específica, sí que te falta limpieza, pero has definido funciones para luego hacer applys, lo cual 👏
        - Las gráficas, ya que las generas, aprovecha a exportarlas para el próximo! (esto no es necesario, pero no está de más)

            ```
            fig.savefig("ruta")

            ```

    Por las circunstancias se te ha quedado a medias, pero no está tan mal como te piensas. Tiene buena estructura, te has lanzado a hacer funciones y has intentado varias formas de hacer algo. Es una exploración/limpieza coherente y por la parte de código está también bien. En cuanto tengas más tiempo ya verás cómo vas a hacer proyectazos. Ánimo Soniaaa 💪

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
