### ISSUE TITLE
[Pandas project] Ángela Navarro

### ISSUE THREAD

**Issue by angelanavarrog** [Ironhack-Data-Madrid-Enero-2021/w2-pandas-project#9]
Here is the link to my repo: https://github.com/angelanavarrog/Sharks-attack---Pandas-project.git

**Comment by angelanavarrog** [comment]
https://github.com/angelanavarrog/Sharks-attack---Pandas-project

**Comment by breogann** [comment]
Hola Ángelaa!! 

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .**gitignore**: todo perfect! No se te ha colado ningún archivo temporal/oculto.
    - Los jupyters, está bien que estén agrupados, pero no son outputs como tal. Output podría ser el dataset ya limpio y las gráficas exportadas.
- El **[README.md](http://readme.md/) ✍🏻**: has creado un archivo que no tiene extensión de mardkwon (.md) y que no se llama`README.md`. Esto es una convención y es la que utiliza github para "renderizar" la portada. Además lo has tratado como un archivo de texto, sin sintaxis de markdown 🔪 esto cámbialo, es importante!

    Respecto a la distribución del readme, está bien, esa es la idea. Siempre le puedes meter más miga:

    - Técnicas concretas que hayas utilizado (gestión de los nulos, applys con funciones, groupby, etc)
    - Gráficas en el readme que hayas generado en los jupyters
    - Las librerías que hayas utilizado, etc.

    Cuando le cambies el nombre al archivo del readme ya verás te aparecen como títulos.

    Por lo demás genial por haber explicitado la hipótesis 👏

- La **modularización 📉**: ¿somos súper pesados con esto? sí. Una vez tengas las funciones aplicadas en jupyter y sepas que funcionen, llévalas a un [archivo.py](http://archivo.py). Para este proyecto no era estrictamente necesario, pero para el resto sí
- El **código 👩‍💻:**
    - Para el renaming: tienes dos formas. Puedes utilizar el métofo rename de pandas como haces y también puedes utilizar el método .strip() si lo que quieres es quitar los espacios.
    - Para limpiar la columna de Y/N, siempre que repitas muchas líneas de código parecidas posiblemente se pueda refactorizar. Puedes por ejemplo pasarlo todo a minúsculas (y así te ahorras una condición para la "n" y otra para la "y"), puedes crear un diccionario, puedes usar strip para quitar los espacios, etc. Simplemente eso, que de cara al futuro si hay muchas líneas parecidas, probablemente se pueda refactorizar.
    - Súper bien definir la función y utilizar un apply 👏:

        ```python
        attacks ["Country"] = attacks["Country"].apply(contains)
        ```

    - Para los datos que son unknown en fatality, quizá los habría droppeado, que al final no te aportan valor.
    - Genial el histplot!
    - El juputer de visualización está muy bien guiado por los títulos y por los comentarios. Graaaciasss por haber puesto las conclusiones. Si no, un story-telling no tendría sentido.

    Como conlusión:

    - Para el siguiente proyecto, tendrás que llevar las funciones a un archivo.py
    - El readmeeeeeee
    - Si hubieras planteado alguna otra hipótesis podrías aprovechado a meter mano a algo más de limpieza.
    - El story-telling con la visualización está genial! Veo que es un planteamiento coherente e hilado.

    Siempre se pueden meter más funciones, pero las que has hecho están bien. 

    Ánimo Ángela (y a tope, que puedes hacer más y verás que echándole tiempo sacas proyectazos)!! 💪🚀

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
